### ISSUE TITLE
Flicking of screen during question

### ISSUE THREAD

**Issue by vogella** [RemainSoftware/AiChat#1]
If I post a question I see a flicking of the screen. Maybe this should look like the matrix but I find it distracting.

![image](https://user-images.githubusercontent.com/139910/234009154-9d57bf7c-c68f-4da7-be1c-781ba2e5a330.png)

**Comment by wimjongman** [comment]
Correct! I have disabled MatrixPonder by default and added a progress indicator in the toolbar. Please update.

![image](https://user-images.githubusercontent.com/180969/234384614-9dace5c2-6e58-4f75-9d7c-ff60030af1e2.png)
