### ISSUE TITLE
Installed the plugin but getting "Error parsing: Read timed out"

### ISSUE THREAD

**Issue by JayGlass** [RemainSoftware/AiChat#10]
Hi, I tried installing the new plugin and I believe I am using it correctlly, I entered the token, and org token but when I try and ask something in chat, I am getting a "Error parsing: Read timed out".  I did see that at one point it said something to the effect of how can I help you today, but subsequent attempts just return the error.  Any thoughts, things I could try?

Eclipse IDE
Version: 2023-03 (4.27.0)
Build id: 20230309-1520
JDK 11

**Comment by wimjongman** [comment]
Please try to restart Eclipse after installing the keys.

**Comment by JayGlass** [comment]
Wow, total newb problem there!  That helped thank you!
![image](https://github.com/RemainSoftware/AiChat/assets/22941261/a34c11a1-90d5-4790-b239-dd8af274d846)

If only coding was as easy as that answer!  Have an awesome day!
