### ISSUE TITLE
Can't login into ChatGpt

### ISSUE THREAD

**Issue by mlitters** [RemainSoftware/AiChat#11]
Hi there,

I just setup your AiChat in RDi 9.8 and entered my API Key and Organization Id.
Then the ChatGpt Signon Window appears. (Password Required)

Whatever I try he doesn't connect.
The Window always reappears.

I am 100% sure that the User and password are correct. I can signing into ChatGpt directly with them.
What can that be?
I am testing on a MacBook Air with M2 and Mac OS Ventura 13.4

I also restarted RDi after entering the Keys.

**Comment by mlitters** [comment]
Hi again,

i also tested it on my Windows Notebook.
Dell XPS with Intel Core I7 12th generation, Windows 11 and RDi 9.8.
Same issue.

I also tested it with RDi 9.6.0.12 - there he doesn't show the Signon Window at all.

Can it be that it is a problem on German systems? Does anybody out there use it in Germany?

The RDi 9.8 is set to English language.

**Comment by mlitters** [comment]
Ok - sorry....
Something went wrong with my API Key.... I am not sure how but it didn't work anymore and therefore the Signon Screen appeared. I created a new one, deleted the old one, tested the new one with Postman and it works and now it also works with ChatAI....

**Comment by wimjongman** [comment]
Thanks for the report and the solution :) Please file enhancement requests on how to include it into IBM i.
