### ISSUE TITLE
unable to get request from API keys and token 

### ISSUE THREAD

**Issue by arjun03abraham** [RemainSoftware/AiChat#16]
I have installed in eclipse, created a API keys and token in OPENAPI.com , paste that API keys in the API chat settings in eclipse but not able to get response while prompting.
help me an alternative solution to solve this issue
![remainAi_chat](https://github.com/RemainSoftware/AiChat/assets/149503562/83f42569-e9fd-4bb2-b959-488da30a84e6)

**Comment by wimjongman** [comment]
Did you restart?
