### ISSUE TITLE
Codepage problem. If cyrylic simbols present

### ISSUE THREAD

**Issue by DitriXNew** [RemainSoftware/AiChat#21]
Question: Дай мені код для валідації банківської картки на C#

Answer: ????? ??????? ????????? ?????????? ????? ?? C# ?????? ?????????? ?????? ??????? ?????????? ???????

**Comment by wimjongman** [comment]
I do not see that.

![image](https://github.com/RemainSoftware/AiChat/assets/180969/115b816f-41b2-4c17-b2fc-466ab7481434)


What is your default encoding?

![image](https://github.com/RemainSoftware/AiChat/assets/180969/e4b382f2-8a18-450f-84ba-6b9b35ae932e)

**Comment by wimjongman** [comment]
Please reopen if the issue persists.
