### ISSUE TITLE
Add RDi Support

### ISSUE THREAD

**Issue by wimjongman** [RemainSoftware/AiChat#4]
Integrate Ai with RDi artifacts.

**Comment by wimjongman** [comment]
After installation a new option is available in the 'New' menu when selecting one or more datafiles.

![image](https://user-images.githubusercontent.com/180969/235315887-b85a47c7-01c8-4bcb-91bd-6c8561f20c29.png)


![image](https://user-images.githubusercontent.com/180969/235316024-37fb8176-66b7-4c81-a10d-394f06d35ee2.png)


![image](https://user-images.githubusercontent.com/180969/235316026-a7929cb5-4c56-4fd5-b67c-3b96a8c0d96f.png)

**Comment by JonFP** [comment]
The instruction "drop it in your RDi dropins folder" is not easily achieved on a Mac.  That folder is only visible once you have selected "Show Package Contents" from the context menu of the RDi application in Finder. Once that is done you can select Contents -> Eclipse and you will see the dropins folder listed there. Drop the jar file on that and all works as expected.

**Comment by wimjongman** [comment]
RDi Support is now done from the update site.
