### ISSUE TITLE
PDF file association - OLE Editor 

### ISSUE THREAD

**Issue by Jmccoach** [RemainSoftware/AiChat#6]
I installed AiChat for RDi 9.6 and after install I received an error for "OLE Editor - no file associated". I had a PDF file open so when the restart of RDi happened I received the same error. I tried to manually associate file extension pdf but that didn't work. I uninstalled AiChat and that fixed the OLE Editor error. Can you help?

**Comment by wimjongman** [comment]
When I doubleclick on a PDF inside Eclipse the PDF is opened in a browser for me.

I don't have to do anything for it but you can also associate the external editor with *pdf like so:

![image](https://user-images.githubusercontent.com/180969/235954347-91367d1a-db83-4000-9d2a-dd81475c23ce.png)

**Comment by Jmccoach** [comment]
For some reason I don't have pdf in my list of file associations. I will add it and then reinstall AiChat. That should fix it. Thanks for the example. Great session you did at COMMON!

**Comment by wimjongman** [comment]
Thanks! I'm glad you liked it. 🙏😁
